//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marafon_I_71.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunnerMarathon
    {
        public int RunnerId { get; set; }
        public int MarathonId { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<System.TimeSpan> TimeResult { get; set; }
    
        public virtual Runner Runner { get; set; }
        public virtual user3 user3 { get; set; }
    }
}
